version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app/everyone-quest-backend #ubuntu는 ec2-hostname
permissions:
  - object: /home/ubuntu/app/everyone-quest-backend/
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
