spring:
  profiles:
    include:
      - core
      - cloud
      - credentials
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/everyone_quest?serverTimezone=Asia/Seoul
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8080