cloud:
  aws:
    s3:
      mock:
        port: 10101
      bucket: 'dev-bucket'
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
